### ISSUE TITLE
找不到Nonebot端的配置文件，需要手动创建吗

### ISSUE THREAD

**Issue by MoEternal** [17TheWord/nonebot-plugin-mcqq#100]
### 运行环境

windows 10、Python3.10、arclight-1.20.1

### NB插件及版本号

NoneBot-Plugin-MCQQ 2.5.7

### MC插件及版本号

MC_QQ_Spigot 2.6.5

### 错误描述

MC服务端可以正常加载插件，BOT也可以正常加载插件，但是连不上BOT和MC服务器
原因是没找到BOT端的配置文件，不清楚在哪里填链接地址和端口，试过手动创建config.yaml和json也没用

**Comment by 17TheWord** [comment]
`nb` 端配置文件一般在机器人的根目录，名为 `.env.dev` 或 `.env.prod`，根据你用 `cli` 生成的模板而定。
另外这部分内容应该查阅 `nb` 文档而非在此提问。

**Comment by MoEternal** [comment]
是我少打了，应该说是此插件在nonebot端的配置文件，就是wiki里的那个

**Comment by 17TheWord** [comment]
> 是我少打了，应该说是此插件在nonebot端的配置文件，就是wiki里的那个

查看你bot目录的 .env.prod 或者.env.dev

**Comment by Junnstoy** [comment]
nb端加载插件是不会自动生成config的，需要自己将Wiki的配置部分复制到.env.*里，然后再修改对应的内容

**Comment by shusiqiang** [comment]
兄弟你的配置文件写好了吗，能参考一下吗，我一直拒绝连接，人麻了

**Comment by 17TheWord** [comment]
> 兄弟你的配置文件写好了吗，能参考一下吗，我一直拒绝连接，人麻了

```dotenv
mc_qq__server_dict = '{
    "Server": {
        "group_list": [
            {
                "group_id": "123123",
                "adapter": "onebot",
                "bot_id": "123123123"
            }
        ],
        "guild_list": [
            {
                "guild_id": "12312312312312312",
                "channel_id": "123123",
                "adapter": "qq",
                "bot_id": "12312312"
            }
        ],
        "rcon_msg": false,
        "rcon_cmd": true
    }
}'
```

**Comment by 17TheWord** [comment]
该issue将被关闭，如有问题请再次打开
