### ISSUE TITLE
【功能建议】增加velocity支持

### ISSUE THREAD

**Issue by Junnstoy** [17TheWord/nonebot-plugin-mcqq#101]
### 插件版本

nonebot-plugin-mcqq, MC_QQ

### 插件版本号

V2.7.0

### 功能建议

是否可以增加velocity群组服的支持呢？

### 额外信息（可选）

举例：在VC群组服中，环境由一个登录服对外ip：0.0.0.0:25565和对内多个子服务器127.0.0.1:30001/30002/30003/30004构成.
目前如果nonebot和服务器在两台主机上，则没有办法针对子服务器进行连接及同步信息。
类似的功能实现：https://github.com/Coloryr/Minecraft_QQ
原作者机器人由C#实现，不太方便进行二次开发，所以想问问是否可以支持，以对接nonebot

**Comment by 17TheWord** [comment]
群组服暂时没有适配的想法，但你或许可以在子服直接安装插件或模组实现？nb这边插件是支持多服务器至多群的。

**Comment by Junnstoy** [comment]
1.对于如果将子服监听从对内转对外，加上rcon控制端口，需要对公打开16个端口，我认为这是不安全的
2.关于信息同步，vc装有子服间的信息同步插件，如果打开消息同步，或许会产生nb的重复信息？（这未经测试）
3.没有计划支持的话，可以关闭此issue了

**Comment by 17TheWord** [comment]
如果不需要rcon的话，端口数不会很多。

对于群组的话短时间是没有计划。对这方面的api也没有了解，不清楚消息会如何上报。

另外就是广播消息需要看群组服广播还是由mcqq广播？

**Comment by 17TheWord** [comment]
已支持Velocity，前往[鹊桥](https://github.com/17TheWord/QueQiao)体验新版
