### ISSUE TITLE
如何修改请求头？

### ISSUE THREAD

**Issue by shusiqiang** [17TheWord/nonebot-plugin-mcqq#103]
### 运行环境

Ubuntu 24.04 LTS、Python3.12

### NB插件及版本号

NoneBot-Plugin-MCQQ v2.5.7

### MC插件及版本号

MC_QQ_Fabric_1.20.1-2.7.1

### 错误描述

如何修改请求头/mcc

**Comment by 17TheWord** [comment]
首先这是命令头，另外暂不支持自定义，可以自行修改插件源码，

**Comment by shusiqiang** [comment]
收到，感谢回复

**Comment by 17TheWord** [comment]
已支持自定义命令头 [wiki](https://github.com/17TheWord/nonebot-plugin-mcqq/wiki/3.-nonebot%E7%AB%AF%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
