### ISSUE TITLE
【功能建议】为插件/模组添加权限节点

### ISSUE THREAD

**Issue by yjcxgjmtd** [17TheWord/nonebot-plugin-mcqq#106]
### 插件版本

MC_QQ

### 插件版本号

v2.7.2

### 功能建议

添加权限节点：
使lp更好设置权限，防止玩家乱用/mcqq reload

**Comment by 17TheWord** [comment]
将下个版本支持

**Comment by 17TheWord** [comment]
三端目前默认普通玩家无权执行，你需要的是否为：在三端都添加权限节点以便用 `luckperms` 分配权限？
还是你碰到了普通玩家可以执行的情况？

**Comment by yjcxgjmtd** [comment]
我们使用的是op制度，所有玩家都是op，在lp中默认组里使用禁权限的方式来禁用部分权限，fabric mod 1.20.1

**Comment by 17TheWord** [comment]
是用lp给所有权限然后去掉某些节点么？

**Comment by yjcxgjmtd** [comment]
对的

**Comment by 17TheWord** [comment]
已在 [`v0.0.5`](https://github.com/17TheWord/QueQiao/releases/tag/v0.0.5) 更新，但未进行充足测试

**Comment by yjcxgjmtd** [comment]
错误的使用方法！此邮箱仅为发送验证码所用！
