### ISSUE TITLE
【错误回报】

### ISSUE THREAD

**Issue by 1409109991** [17TheWord/nonebot-plugin-mcqq#11]
### 运行环境

Windows Server 2016

### 插件版本

nonebot-plugin-mcqq-mcrcon

### 插件版本号

V1.0.0

### 错误描述

![image](https://user-images.githubusercontent.com/79674967/193286838-580cb629-9a6b-4e1b-8166-bfa73f2eab01.png)
这是什么问题

**Comment by 17TheWord** [comment]
Python版本是多少？
是否为3.10？

**Comment by 1409109991** [comment]
3.9，我自己搞好了，| 改成 or 就行了

**Comment by 17TheWord** [comment]
好的，没有问题的话就关闭了

**Comment by 1409109991** [comment]
还有，我这都好了，也没报错，游戏里消息没有互通

**Comment by 17TheWord** [comment]
有认真按照文档操作吗？

**Comment by 1409109991** [comment]
配置都好的，没有报错，就发消息没反应

**Comment by 1409109991** [comment]
用你叙述文件里推荐的那个mc插件，群消息能发到mc里，游戏里的发不出去

**Comment by 1409109991** [comment]
睡觉，明天再重新搞一下。

**Comment by 17TheWord** [comment]
如果用mcrcon版本配置有困难的话，可以使用普通的mcqq版本，只需要mc server与bot在同一台机器即可，不需要配置过多连接信息，功能目前阶段也是相同。

**Comment by 1409109991** [comment]
![image](https://user-images.githubusercontent.com/79674967/193376925-27f36142-eab2-46e4-addb-64d68d28e72a.png)
![image](https://user-images.githubusercontent.com/79674967/193376940-f44ce751-99e5-4cc0-ab02-e7d56137d6ee.png)
![image](https://user-images.githubusercontent.com/79674967/193376948-9134b75d-b9a7-449b-b1d5-5af7d99b939f.png)

**Comment by 1409109991** [comment]
![image](https://user-images.githubusercontent.com/79674967/193377010-9ba64e81-f6b0-45c4-b9b1-492dcd536167.png)

**Comment by 1409109991** [comment]
还是没反应

**Comment by 17TheWord** [comment]
可以的话发送一下联系方式，我远程帮助下。

**Comment by 17TheWord** [comment]
- [`TypeError`](https://github.com/17TheWord/nonebot-plugin-mcqq/issues/11#issue-1392493588) 将会在下一个版本修复
- 消息判断类型会从 `isinstance` 改为 判断 `event.message_type` 字符串
- 新增 `Forge_Server` 程序

**Comment by 17TheWord** [comment]
已在 [`v0.1.1`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.1.2) 修复
