### ISSUE TITLE
【功能建议】增加一个查看在线人数的指令

### ISSUE THREAD

**Issue by 1409109991** [17TheWord/nonebot-plugin-mcqq#12]
### 插件版本

nonebot-plugin-mcqq-mcrcon

### 插件版本号

V1.0.0

### 功能建议

加一个查看在线人数的指令。 （mc端不能指令的话）
这个应该不难吧，通过计算加入和退出的人来搞，不影响mc端。
如果能执行mc指令也行

**Comment by 17TheWord** [comment]
已在 [`v0.1.3`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.1.3) 更新
