### ISSUE TITLE
【功能建议】添加个可以设置某些前缀不转发的功能

### ISSUE THREAD

**Issue by Tamamoimoto** [17TheWord/nonebot-plugin-mcqq#121]
### 插件版本

nonebot-plugin-mcqq

### 插件版本号

V2.6.2

### 功能建议

希望能设置个功能，用来设置屏蔽某些符号开头的语句不转发。比如./！\等。

### 额外信息（可选）

nonebot2+mirai+Dice大融合的BOT，会转发指令进入游戏中，希望能屏蔽带符号的语句。

**Comment by 17TheWord** [comment]
群到游戏的消息还是游戏到群的消息？

**Comment by Tamamoimoto** [comment]
> 群到游戏的消息还是游戏到群的消息？

群到游戏的消息

**Comment by 17TheWord** [comment]
行

**Comment by 17TheWord** [comment]
需要过滤的消息中，前缀有一位字符还是多位字符？

**Comment by Tamamoimoto** [comment]
> 需要过滤的消息中，前缀有一位字符还是多位字符？

一位字符即可，如.或/或!

**Comment by 17TheWord** [comment]
更新工具包使用 `pip install mcqq-tool==1.3.2`，未测试，有问题再改

**Comment by 17TheWord** [comment]
好像忘了放使用方法
```dotenv
mc_qq__ignore_message_header=[".", "/"]
```
