### ISSUE TITLE
【功能建议】Minecraft端消息建议改为群名片

### ISSUE THREAD

**Issue by Cloudwhile** [17TheWord/nonebot-plugin-mcqq#16]
### 插件版本

nonebot-plugin-mcqq

### 插件版本号

V1.0.0

### 功能建议

Minecraft端消息建议改为群名片

**Comment by 17TheWord** [comment]
已在 [`v0.1.2`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.1.2) 添加功能
