### ISSUE TITLE
【功能建议】阻断消息传播

### ISSUE THREAD

**Issue by yzyyz1387** [17TheWord/nonebot-plugin-mcqq#20]
### 插件版本

nonebot-plugin-mcqq-mcrcon

### 插件版本号

latest

### 功能建议

一条不太重要的issue
插件是不是会阻断消息的传播？具体我没去看源码，但在我的环境下使用本插件，优先级比较低其他插件命令无法被捕捉到

**Comment by 17TheWord** [comment]
很感谢你的反馈
优先级方面是有点低
因为我也是第一次写这样的插件，对于一个优先级的拿捏并不准确
同时是准备在自己的使用过程中不断探索一个合适的优先级

- 感觉可以把 [`Block`](https://nb2.baka.icu/docs/tutorial/plugin/create-matcher#%E9%98%BB%E6%96%AD-block)，设为 `False`，但可能会把某些其他插件的命令消息也一并发送到游戏中
- 或许可以默认设为 `1` ，通过修改配置的方式让用户自行选择一个合适的优先级
- 如果要传递更多消息的话，你可以先自行设置优先级解决。
- 如果你有更好的建议的话还请帮助我完成它

**Comment by yzyyz1387** [comment]
emmm，我的意思是，不考虑贵插件的优先级，我的其他插件，优先级比较低的会被贵插件阻断，所以，我提的问题关键在于mcrcon 会阻断消息，（关于阻断:  https://v2.nonebot.dev/docs/tutorial/plugin/create-matcher#%E9%98%BB%E6%96%AD-block）
 ，而不是他的优先，如果是我，解决方法可能会是：
- 在配置文件中指定开启插件的群聊：
  - 另起配置来决定是否阻断（在mc服务器群阻断消息，只实现消息互通，而不会拉起其他插件，单只消息刷屏，效果可能会好点），且配置是可以根据命令动态修改，（但是有的用户他又不在乎，所以也可以不阻断）
- 不在指定群：
  - 放行所有消息


若bot单纯只开了 mcrcon ，则不必考虑这些，但考虑到用户会安装其他插件，所以...

大概是这么个意思，供参考，也有可能我说的是废话（免责声明）
贵插件很棒，边mc边聊天体验很不错哈哈

**Comment by yzyyz1387** [comment]
我bot在服务器，日志我没看，我也是猜测应该是阻断导致用不了其他插件的
![image](https://user-images.githubusercontent.com/51691024/202980279-16f6783a-cb03-4fd5-8f87-ec710f395eb5.png)

**Comment by 17TheWord** [comment]
关于动态修改配置文件，其实老早就想做了，不过能力不够，写不出来。
这个插件，也是老早就有想法了，慢慢学习才做出来。
不过这个想法很好，最近事情有点多，还有一个修复了两个小问题的版本还没放出来，打算空闲了一并放出来

**Comment by yzyyz1387** [comment]
动态修改配置文件还是挺简单的，涉及路径文件相关的推荐`pathlib`
## 一般我会用`path.py`来装所有的相关路径
```python
from pathlib import Path

LOCAL = Path() / 'mcqq'  #Path()会是 `bot.py` 所在路径，所以这里代表 `机器人项目/mcqq`
USER_CONFIG_PATH = LOCAL / 'user_config.txt'  #这里是最简单的txt，一般我用 json 或者 yml
OTHER_CONFIG_PATH = LOCAL / 'other_config.yml'
....

```

## 在插件初始化时
什么时候初始化由你决定
- 在bot连接时（例子：[例子](https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/config.py#L20)）
```python
from nonebot import get_driver, logger
from .path import *

driver = get_driver()


@driver.on_bot_connect
async def _():
    LOCAL.mkdir() if not LOCAL.exists() else ...  #在初始化时创建我们需要的文件夹（如果没有这个文件夹）
    logger.info('mcqq初始化检测完成')
```

- 或者在输入`初始化`指令时，或者其他的

初始化主要是创建文件夹，文件的话需要时再读写

## 主要是给你说下pathlib的常用方法
没看过官方文档，我经常用 Path就够了，给你现找了个[Python使用pathlib库](http://www.qb5200.com/article/487180.html)
```python
# 创建文件夹

xxx.mkdir()
# 创建空文件

xxx.touch()
# 删除文件夹

xxx.rmdir()

# 删除文件
xxx.unlink()

# 读取文件文本（就是open在read,读出来是str）.
xxx.read_text(encoding="utf-8")
# 这里要是json或者yml文件，再用相关的包 load 成 py 对象就行


```
反正就是读写文件嘛，txt的话直接读写，缺点在不好解析不好用，yaml就用yaml库，json 就用json库，我的屎山代码就不往这儿放了哈哈
我写插件大多就是这个套路，希望对你有帮助

**Comment by 17TheWord** [comment]
非常感谢你的帮助
---
- 最初的动态配置我是想通过 `tortoise` 操作 `sqlite` 实现，因为我改过 `SK` 佬的 `HarukaBot` 使其通过频道补丁适配到频道，这个过程中用到了 `tortoise`。
- 修改本地文件的话，感觉相对来说比较简单，可以考虑。

同时有想过让插件支持不同服务器到不同群的消息互通，同时萌生了一个写出 `noenbot-adapter-spigot` 的想法（这只是一张大饼），但现在建立的 `WebSocket` 是以 `Bot` 为客户端，`MC Server` 为服务端。

想实现 `adapter` 需要转变客户端与服务端的位置，目前还在思考并尝试开发中。
最初的首选是用数据库来管理，现在看来使用本地文件也未尝不可。

慢慢尝试吧，终究会做出来的。另外关于 `block`、`rule` 以及其他两个小问题已在[`v0.1.4`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.1.4)中更新

**Comment by yzyyz1387** [comment]
可以，数据库那个也好用，加油！

**Comment by 17TheWord** [comment]
还有另外一种可能，早在很多个版本之前。插件是采用的是用户自己手写配置文件的方式

只不过到现在很久了我给忘了。今天再次写配置文件想起来了。
