### ISSUE TITLE
【错误反馈】玩家死亡ws断连

### ISSUE THREAD

**Issue by zhzhongshi** [17TheWord/nonebot-plugin-mcqq#26]
### 运行环境

Ubuntu下python3.9运行nb2 rc2 和本插件 win上运行Paper-1.12.2

### 插件版本

nonebot-plugin-mcqq, MC_QQ

### 插件版本号

1.0.6

### 错误描述

使用/kill命令 ws断开连接，期间不传输消息
log见附件
[paper.log](https://github.com/17TheWord/nonebot-plugin-mcqq/files/10348477/paper.log)
[nb2.log](https://github.com/17TheWord/nonebot-plugin-mcqq/files/10348483/nb2.log)

### 报错日志（如果有）

```bash
太大，见上
```

**Comment by 17TheWord** [comment]
检查完毕，原因是Spigot中死亡消息没有转化为Json
已解决，在该comment后前往 [`v1.0.6`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v1.0.6) 下载修复过的插件
