### ISSUE TITLE
【错误反馈】服内消息无法转发到群里（WS服务器断开）

### ISSUE THREAD

**Issue by DeadBoy2537** [17TheWord/nonebot-plugin-mcqq#34]
### 运行环境

Ubuntu 22.04

### 插件版本

MC_QQ

### 插件版本号

v1.0.8

### 错误描述

群内发送的消息可以转到服务器里，但服务器里的消息很多都转不出去
因为没有QQ频道，所以我在.env.dev文件里是这样写的:

MC_QQ_SERVERS_LIST = [{"server_name": "服务器", "group_list": [群号]}]

也许就是这个有问题

### 报错日志（如果有）

![IMG_20230126_122055](https://user-images.githubusercontent.com/87133530/214759326-c10f3937-de70-4897-ba74-bc34f2b7e207.jpg)
![IMG_20230126_122119](https://user-images.githubusercontent.com/87133530/214759338-2769fb9d-fc7b-4f7d-8cc9-316a63d9fbf3.jpg)

**Comment by DeadBoy2537** [comment]
![IMG_20230126_122055](https://user-images.githubusercontent.com/87133530/214759214-bc7ad5f5-1f8f-4c5b-9467-b54894e754f5.jpg)
![IMG_20230126_122119](https://user-images.githubusercontent.com/87133530/214759222-c0558754-2305-45b8-9035-aef654d0bbcf.jpg)

**Comment by 17TheWord** [comment]
该问题与配置无关。
可能是你关服没有正常关闭导致websocket这边没有收到正常关闭信息，没有收到关闭信息，则不会将列表中的服务器清除。

重启nb即可。

**Comment by DeadBoy2537** [comment]
嗯...
![IMG_20230126_140742](https://user-images.githubusercontent.com/87133530/214769212-72938dcc-8117-491e-ae55-5b492e613ddb.jpg)
服务端和机器人都重启了

**Comment by 17TheWord** [comment]
发一下你的env配置，有关mcqq所有的配置。

可以的话，请加入交流群提供更多信息

**Comment by 17TheWord** [comment]
我刚测试了一遍，无法复现你的错误，使用正常

**Comment by DeadBoy2537** [comment]
![IMG_20230126_162801](https://user-images.githubusercontent.com/87133530/214789749-0eab5487-c371-4705-a29a-85c28587a5d1.jpg)
![IMG_20230126_162718](https://user-images.githubusercontent.com/87133530/214789765-b428ba53-2f3e-4c46-9b30-9c7c7d3be15c.jpg)
机器人是https://github.com/HibiKier/zhenxun_bot
