### ISSUE TITLE
【错误反馈】消息只能被单向转发（游戏->群聊）

### ISSUE THREAD

**Issue by dixiatielu** [17TheWord/nonebot-plugin-mcqq#35]
### 运行环境

Ubuntu 22.04 LTS、Python3.10、PufferFIsh-1.19.3

### NB插件及版本号

nonebot-plugin-mcqq 1.0.8

### MC插件及版本号

MC_QQ_Spigot_1.14+ 1.0.8

### 错误描述

nonebot端与MC服务端不在同一物理机上，通过公网连接
将nonebot端的8765端口开放至公网，MC服务端通过ip连接到bot服务器。
在游戏中发送消息可以成功通过bot转发至群聊，但在群聊中发送任何消息都不会被转发至服务器
应该是nonebot端的问题，因为观察nonebot的日志发现消息只是被handle了，之后没有任何关于MCQQ的log（）
```
01-29 21:55:50 [SUCCESS] nonebot_plugin_mcqq | [MC_QQ]丨[Server:????] 已连接至 WebSocket 服务器
01-29 21:56:13 [SUCCESS] nonebot_plugin_mcqq | [MC_QQ]丨from [纯净生存] to [群:1079084078] "[纯净生存] dixiatielu 加入了服务器"
01-29 21:56:17 [SUCCESS] nonebot | OneBot V11 3629717836 | [message.group.normal]: Message 1113833086 from 1397749594@[群:1079084078] "bbb"
01-29 21:56:17 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mcqq)
01-29 21:56:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mcqq) running complete
```
MC服务端控制台在发送群消息后也无任何反应，应该是没有接收到bot端发送的消息

通过在nonebot端的插件代码`data_source.py`处进行如图修改后：
![image](https://user-images.githubusercontent.com/29675002/215332353-96fb9b5d-9fd9-447d-a693-1dace52bb0cb.png)
再次运行插件，发现nonebot控制台报错如图（client为空）：
![image](https://user-images.githubusercontent.com/29675002/215332345-ade4cd40-4bf8-4d06-a912-d35d2b499ce2.png)

又对get_client函数进行如下更改后：
![image](https://user-images.githubusercontent.com/29675002/215333755-5ffad474-30d9-4f20-9457-c5ef456ba098.png)
发现nonebot端错误：
![image](https://user-images.githubusercontent.com/29675002/215333799-90b371fa-fb61-4598-b001-5cffd01dcaaf.png)
判断问题是由于MC端的server-name设置为中文，但nonebot端未正确读取造成的。经排查，MC服务器端`config.yml`与nonebot端.env文件均使用相同编码UTF-8，可能是在websocket传输中出现了错误。希望作者考虑排查一下编码原因。

在将`config.yml`与`.env`文件中的服务器名称均改为相同的英文后，问题得以解决。

**Comment by 17TheWord** [comment]
插件配置文件的编码一直是Java版服务端让人麻烦的问题
如果是Win系统，将插件的配置文件编码格式改为GBK
如果是Linux，改为UTF-8

**Comment by dixiatielu** [comment]
> 插件配置文件的编码一直是Java版服务端让人麻烦的问题 如果是Win系统，将插件的配置文件编码格式改为GBK 如果是Linux，改为UTF-8

MC端与nonebot端均为Ubuntu Linux系统，配置文件编码也均为UTF-8，但此问题仍然存在😢😢

**Comment by 17TheWord** [comment]
> MC端与nonebot端均为Ubuntu Linux系统，配置文件编码也均为UTF-8，但此问题仍然存在😢😢

这种问题我应该没遇到过，可以加一下交流群给我看更多信息？

**Comment by 17TheWord** [comment]
现版本暂无法使用中文命名服务器，将在后续修复

**Comment by dixiatielu** [comment]
#38  #39 已修复
