### ISSUE TITLE
【错误反馈】1.14+插件内未含有plugin.yml导致插件报错,无法被加载

### ISSUE THREAD

**Issue by Dango0706** [17TheWord/nonebot-plugin-mcqq#42]
### 运行环境

无

### NB插件及版本号

无

### MC插件及版本号

1.1.0 spigot1.19.2

### 错误描述

plugin.jar内无plugin.yml 导致插件无法被加载

**Comment by 17TheWord** [comment]
已重新编译，重新 [下载](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/download/v1.1.0/MC_QQ_Spigot_1.14+.jar) 即可

**Comment by 17TheWord** [comment]
如果问题解决，请关闭issue
