### ISSUE TITLE
【功能建议】Forge Mod对更广泛的Minecraft版本的支持

### ISSUE THREAD

**Issue by yutianzeabc** [17TheWord/nonebot-plugin-mcqq#45]
### 插件版本

Minecraft_Server

### 插件版本号

v.1.1.1

### 功能建议

当前的Forge Mod要求MC版本为1.19.1，希望添加较低版本的Forge Mod支持，例如1.12.2~

**Comment by 17TheWord** [comment]
我近一段时间没有空余时间，如有能力可自行前往 [forge](https://github.com/17TheWord/nonebot-plugin-mcqq/tree/forge_mod) 分支参考并，欢迎提交PR。
或者等一段时间之后我尝试更新。

**Comment by yutianzeabc** [comment]
好的，期待作者更新~

**Comment by 17TheWord** [comment]
现阶段也有读取日志的方式可以凑合使用

**Comment by yutianzeabc** [comment]
好的，我研究一下，不过如果能有Forge Mod的话肯定是更好的~

**Comment by 17TheWord** [comment]
还有一个问题就是，我对forge了解不多，编译可能是需要对每个版本都编译一次？版本太多了当时就没做其他的。

**Comment by yutianzeabc** [comment]
据我所知的话，大部分的Forge Mod采用的是每个MC大版本（例如1.12-1.12.2）打个jar包的方式；但也有少数Mod采取了特殊的方式兼容了不同的MC版本，如[I18nUpdateMod3](https://github.com/CFPAOrg/I18nUpdateMod3)，不过目测实现方式比较复杂，具体设计上也有一定限制。

**Comment by 17TheWord** [comment]
> 据我所知的话，大部分的Forge Mod采用的是每个MC大版本（例如1.12-1.12.2）打个jar包的方式；但也有少数Mod采取了特殊的方式兼容了不同的MC版本，如[I18nUpdateMod3](https://github.com/CFPAOrg/I18nUpdateMod3)，不过目测实现方式比较复杂，具体设计上也有一定限制。

一个大版本一个Mod吗？还是插件方便点，部分功能直接1.12或者1.14直接到最新都可以用

**Comment by yutianzeabc** [comment]
确实，Forge这块我涉及不多，但据我了解Forge的各版本API变动有大量的Breaking Change，向前兼容/向后兼容性上是不如Bukkit插件的。

**Comment by yutianzeabc** [comment]
不过，我想如果采用分版本发布的方式，也可以考虑先支持用户相对较多的MC/Forge版本，如1.12+、1.16+、1.18+、1.19+

**Comment by 17TheWord** [comment]
对Forge Mod做了一些重构，1.19.1源码已经发布在新的仓库 [MC_QQ_Forge](https://github.com/17TheWord/MC_QQ_Forge)
其他版本正在写

**Comment by yutianzeabc** [comment]
嗯嗯，已经Star了~

**Comment by 17TheWord** [comment]
[QueQiao-forge+1.12.2-0.1.1.zip](https://github.com/user-attachments/files/20245048/QueQiao-forge%2B1.12.2-0.1.1.zip)
https://github.com/17TheWord/QueQiao/issues/46
