### ISSUE TITLE
插件无法加载mcqq_tool这个依赖

### ISSUE THREAD

**Issue by PackageInstaller** [17TheWord/nonebot-plugin-mcqq#49]
装了后
![image](https://user-images.githubusercontent.com/80018096/236627269-5069b908-d99a-437a-b0f0-ec1bbde03871.png)

去/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/mcqq_tool这个目录看了下_init_.py里面是空的，大佬帮忙看看怎么解决吧

系统:**6.3.1-arch1-1**
bot:**zhenxun_bot**
python3.11.3

**Comment by 17TheWord** [comment]
尝试卸载 `pip uninstall mcqq-tool`，然后重新安装 `pip install mcqq-tool`

**Comment by PackageInstaller** [comment]
已尝试过，还是空白

**Comment by 17TheWord** [comment]
尝试更新插件，`pip install -U nonebot-plugin-mcqq`，如果还不行，`pip show nonebot-plugin-mcqq` 查看你的版本号

**Comment by PackageInstaller** [comment]
pip install -U nonebot-plugin-mcqq后问题解决，寒邪大佬解答
