### ISSUE TITLE
【错误反馈】乱码

### ISSUE THREAD

**Issue by Mulsd** [17TheWord/nonebot-plugin-mcqq#58]
### 运行环境

Windows10 22h2

### NB插件及版本号

latest

### MC插件及版本号

Fabric端插件，最新版

### 错误描述

读取服务器聊天中文内容时会乱码
不会java，从网上试了java -Dfile.encoding=gbk -jar 也不行，只要是中文就乱码
服务器（RCON）是运行在docker里面的，jar插件是运行在win下的，不知道是不是这个导致出现问题
还望指导一下

**Comment by 17TheWord** [comment]
信息太少了，没法判断

**Comment by Mulsd** [comment]
只有截图可以吗
命令是java -Xms512m -Xmx512m -jar MinecraftServer.jar
![IAU@EYD4K0DBZ}O`3B18)IL](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/49836364/49fbf4bf-f7ba-4219-989d-497b7a1bd7f0)
![FUFVE51NH2ZH0AMXPBVQ1ND](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/49836364/5e147aad-2d78-4812-bb8e-3607a060f71b)
![4%9 0~BC9459BX7 T93_ {V](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/49836364/93c494ff-df96-486d-9fba-5288ff9986f0)

**Comment by 17TheWord** [comment]
尝试过几次，但水平较低，没能找到适用通用的方法，我本地运行没问题

**Comment by ilworkcn** [comment]
乱码的原因是LINUX默认使用UTF-8编码输出的latest.log日志文件，但是此java程序使用的是GBK编码，要解决乱码问题只需要在服务端执行参数上添加 -Dfile.encoding=GBK 即可，在此程序启动参数上添加编码参数无用。

**Comment by 17TheWord** [comment]
> 乱码的原因是LINUX默认使用UTF-8编码输出的latest.log日志文件，但是此java程序使用的是GBK编码，要解决乱码问题只需要在服务端执行参数上添加 -Dfile.encoding=GBK 即可，在此程序启动参数上添加编码参数无用。

感谢指出问题并提供解决方法。
