### ISSUE TITLE
【错误反馈】（在此简单描述碰到的问题）

### ISSUE THREAD

**Issue by ayakasuki** [17TheWord/nonebot-plugin-mcqq#59]
### 运行环境

ubuntu20.04LTS

### NB插件及版本号

1.2.6post1

### MC插件及版本号

1.2.6post1

### 错误描述

![image](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/20859971/9ad0eb44-629d-4fdb-82d0-e28fe71fad92)
经常可能网络波动时，出现这种错误

**Comment by 17TheWord** [comment]
暂时没有复现经常性的网络波动
