### ISSUE TITLE
关于mcqq的阻塞

### ISSUE THREAD

**Issue by ayakasuki** [17TheWord/nonebot-plugin-mcqq#60]
### 运行环境

ubuntu20.04LTS

### NB插件及版本号

1.2.6post1

### MC插件及版本号

1.2.6post1和1.20.1

### 错误描述

我发现互通消息的群聊，会阻塞其他命令的功能，比如mcqq把消息发到mc以后，别的插件命令不触发了。。。

**Comment by 17TheWord** [comment]
看[这段代码](https://github.com/17TheWord/nonebot-plugin-mcqq/blob/31272ebc91949ec4a25f900af2c799b413815534/nonebot_plugin_mcqq/__init__.py#L32)

只有命令开启了block

```python
mc_qq_cmd = on_command("minecraft_command", aliases={"mcc"}, priority=1, rule=msg_rule, block=True)
```

**Comment by ayakasuki** [comment]
> 看[这段代码](https://github.com/17TheWord/nonebot-plugin-mcqq/blob/31272ebc91949ec4a25f900af2c799b413815534/nonebot_plugin_mcqq/__init__.py#L32)
> 
> 只有命令开启了block
> 
> ```python
> mc_qq_cmd = on_command("minecraft_command", aliases={"mcc"}, priority=1, rule=msg_rule, block=True)
> ```

奇怪 我去掉那个block=True 也不行

**Comment by ayakasuki** [comment]
```08-13 12:20:28 [SUCCESS] nonebot | ONEBOT V11 1219738090 | [message.group.normal]: Message 233366186 from 542149277@[群:904713292] "/地图"
08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False>
08-13 12:20:28 [SUCCESS] mcqq_tool | [MC_QQ_Rcon]丨发送至 [server:1.20.1] 的消息 "桃子 说：/地图"
08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False> running complete``` 
这是日志，到`Matcher <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False> running complete`就没后续了

**Comment by ayakasuki** [comment]
> ```
> 08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
> 08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
> 08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
> 08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
> 08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
> 08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
> 08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
> 08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
> 08-13 12:20:28 [INFO] nonebot | Event will be handled by <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False>
> 08-13 12:20:28 [SUCCESS] mcqq_tool | [MC_QQ_Rcon]丨发送至 [server:1.20.1] 的消息 "桃子 说：/地图"
> 08-13 12:20:28 [INFO] nonebot | Matcher <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False> running complete``` 
> ```

这是日志，到Matcher <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False> running complete就没后续了

**Comment by Heartfirey** [comment]
请问问题解决了吗，我好像也碰到了阻塞消息的问题

**Comment by 17TheWord** [comment]
> 请问问题解决了吗，我好像也碰到了阻塞消息的问题

你在什么情况下遇到了什么阻塞问题，发出日志，按道理来说已经算是重构了一遍了，能阻塞的也就 `Rcon` 了吧

**Comment by Heartfirey** [comment]
配置环境：Windows+poetry+Nonebot2 latest release
主要问题：先不管命令，监听的群里的消息都会被mcqq的handler给处理掉，其他插件的命令都会失效（已经设置了命令的lead是反斜杠了）
打个比方，刚刚随便找了一个游戏插件：
```
06-17 18:16:07 [SUCCESS] nonebot | OneBot V11 xxx | [message.group.normal]: Message -2147483439 from xxxxxx '赛马创建'                                                    06-17 18:16:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=22)                                                                      06-17 18:16:08 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=22) running complete
```
而在未监听的群里：
```
06-17 18:16:16 [SUCCESS] nonebot | OneBot V11 3556507114 | [message.group.normal]: Message -2147483438 from 1754989931@[群:858252683] '赛马创建'                                                    06-17 18:16:17 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_clovers, lineno=71)                                                                          06-17 18:16:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_clovers, lineno=71) running complete
```
可能是我配置的问题（？）但是我并没有找到消息类型相关的配置

**Comment by 17TheWord** [comment]
> 配置环境：Windows+poetry+Nonebot2 latest release 主要问题：先不管命令，监听的群里的消息都会被mcqq的handler给处理掉，其他插件的命令都会失效（已经设置了命令的lead是反斜杠了） 打个比方，刚刚随便找了一个游戏插件：
> 
> ```
> 06-17 18:16:07 [SUCCESS] nonebot | OneBot V11 xxx | [message.group.normal]: Message -2147483439 from xxxxxx '赛马创建'                                                    
> 06-17 18:16:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=22)                                                                      
> 06-17 18:16:08 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=22) running complete
> ```
> 
> 而在未监听的群里：
> 
> ```
> 06-17 18:16:16 [SUCCESS] nonebot | OneBot V11 xxxx | [message.group.normal]: Message -2147483438 from xxxxx '赛马创建'                                                    
> 06-17 18:16:17 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_clovers, lineno=71)                                                                          
> 06-17 18:16:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_clovers, lineno=71) running complete
> ```
> 
> 可能是我配置的问题（？）但是我并没有找到消息类型相关的配置


看了下代码，消息并没有设置阻塞，而且比命令都低一个等级，你不妨手动改下代码试试，把priority往大了调整试试看，注意让命令比消息优先一个级别。

```python
on_qq_msg = on_message(priority=5, rule=all_msg_rule)

on_qq_cmd = on_command("minecraft_command", rule=all_msg_rule, aliases={"mcc"}, priority=4, block=True)

on_qq_send_title_cmd = on_command("send_title", rule=all_msg_rule, aliases={"mcst"}, priority=4, block=True)

on_qq_action_bar_cmd = on_command("action_bar", rule=all_msg_rule, aliases={"mca"}, priority=4, block=True)
```

**Comment by Heartfirey** [comment]
OK，谢谢🙏

**Comment by 17TheWord** [comment]
> OK，谢谢🙏

将消息改到99，命令改到98试试

**Comment by Heartfirey** [comment]
> > OK，谢谢🙏
> 
> 将消息改到99，命令改到98试试

确实，我改了个比较大的值之后是可以的了👌
