### ISSUE TITLE
【错误反馈】nonebot无法加载

### ISSUE THREAD

**Issue by F1Justin** [17TheWord/nonebot-plugin-mcqq#62]
### 运行环境

macOS 14.0, fabric 1.20.1

### NB插件及版本号

1.2.7

### MC插件及版本号

1.2.7

### 错误描述

使用命令nb plugin install nonebot-plugin-mcqq安装，启动nonebot后提示加载错误（

### 报错日志（如果有）

```bash
10-08 13:20:57 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/Users/justin/miniconda3/envs/bot/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot_plugin_mcqq/__init__.py", line 8, in <module>
    from nonebot.drivers import ASGIMixin
ImportError: cannot import name 'ASGIMixin' from 'nonebot.drivers' (/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/drivers/__init__.py)
```

**Comment by 17TheWord** [comment]
你的nonebot2版本是否 v2.1.1，如果不是请更新

**Comment by F1Justin** [comment]
刚刚更新了，仍旧加载错误，日志如下
pip install --upgrade nb-cli nonebot2 nonebot-adapter-cqhttp
Requirement already satisfied: nb-cli in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (1.2.5)
Requirement already satisfied: nonebot2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (2.0.1)
Collecting nonebot2
  Obtaining dependency information for nonebot2 from https://files.pythonhosted.org/packages/68/06/eb8f6d6484f2b1bd71e687d308e436ca5b312adcd2d6a232003080846ede/nonebot2-2.1.1-py3-none-any.whl.metadata
  Downloading nonebot2-2.1.1-py3-none-any.whl.metadata (20 kB)
Collecting nonebot-adapter-cqhttp
  Downloading nonebot_adapter_cqhttp-2.0.0b1-py3-none-any.whl (1.7 kB)
Requirement already satisfied: anyio~=3.6 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (3.7.1)
Requirement already satisfied: cashews~=6.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (6.2.0)
Requirement already satisfied: click~=8.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (8.1.6)
Requirement already satisfied: cookiecutter~=2.2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (2.2.3)
Requirement already satisfied: httpx~=0.18 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (0.24.1)
Requirement already satisfied: importlib-metadata>=4.6 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (6.8.0)
Requirement already satisfied: jinja2~=3.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (3.1.2)
Requirement already satisfied: noneprompt<1.0.0,>=0.1.9 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (0.1.9)
Requirement already satisfied: pydantic~=1.9 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (1.10.12)
Requirement already satisfied: pyfiglet<1.0.0,>=0.8.post1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (0.8.post1)
Requirement already satisfied: tomlkit~=0.10 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (0.12.1)
Requirement already satisfied: typing-extensions~=4.4 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (4.7.1)
Requirement already satisfied: virtualenv~=20.21 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (20.24.5)
Requirement already satisfied: watchfiles~=0.16 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (0.19.0)
Requirement already satisfied: wcwidth~=0.2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nb-cli) (0.2.6)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nonebot2) (0.6.0)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nonebot2) (2.5.0)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nonebot2) (2.0.1)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nonebot2) (1.9.2)
Requirement already satisfied: nonebot-adapter-onebot in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nonebot-adapter-cqhttp) (2.2.3)
Requirement already satisfied: idna>=2.8 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from anyio~=3.6->nb-cli) (3.4)
Requirement already satisfied: sniffio>=1.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from anyio~=3.6->nb-cli) (1.3.0)
Requirement already satisfied: exceptiongroup in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from anyio~=3.6->nb-cli) (1.1.2)
Requirement already satisfied: binaryornot>=0.4.4 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from cookiecutter~=2.2->nb-cli) (0.4.4)
Requirement already satisfied: pyyaml>=5.3.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from cookiecutter~=2.2->nb-cli) (6.0.1)
Requirement already satisfied: python-slugify>=4.0.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from cookiecutter~=2.2->nb-cli) (8.0.1)
Requirement already satisfied: requests>=2.23.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from cookiecutter~=2.2->nb-cli) (2.31.0)
Requirement already satisfied: arrow in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from cookiecutter~=2.2->nb-cli) (1.2.3)
Requirement already satisfied: certifi in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from httpx~=0.18->nb-cli) (2023.7.22)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from httpx~=0.18->nb-cli) (0.17.3)
Requirement already satisfied: zipp>=0.5 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from importlib-metadata>=4.6->nb-cli) (3.16.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from jinja2~=3.0->nb-cli) (2.1.3)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.19 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from noneprompt<1.0.0,>=0.1.9->nb-cli) (3.0.39)
Requirement already satisfied: python-dotenv>=0.10.4 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from pydantic~=1.9->nb-cli) (1.0.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from virtualenv~=20.21->nb-cli) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12.2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from virtualenv~=20.21->nb-cli) (3.12.2)
Requirement already satisfied: platformdirs<4,>=3.9.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from virtualenv~=20.21->nb-cli) (3.11.0)
Requirement already satisfied: multidict>=4.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2) (6.0.4)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from nonebot-adapter-onebot->nonebot-adapter-cqhttp) (1.0.5)
Requirement already satisfied: chardet>=3.0.2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from binaryornot>=0.4.4->cookiecutter~=2.2->nb-cli) (5.1.0)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from httpcore<0.18.0,>=0.15.0->httpx~=0.18->nb-cli) (0.14.0)
Requirement already satisfied: text-unidecode>=1.3 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from python-slugify>=4.0.0->cookiecutter~=2.2->nb-cli) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from requests>=2.23.0->cookiecutter~=2.2->nb-cli) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from requests>=2.23.0->cookiecutter~=2.2->nb-cli) (2.0.4)
Requirement already satisfied: python-dateutil>=2.7.0 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from arrow->cookiecutter~=2.2->nb-cli) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages (from python-dateutil>=2.7.0->arrow->cookiecutter~=2.2->nb-cli) (1.16.0)
Downloading nonebot2-2.1.1-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.4/101.4 kB 889.0 kB/s eta 0:00:00
Installing collected packages: nonebot2, nonebot-adapter-cqhttp
  Attempting uninstall: nonebot2
    Found existing installation: nonebot2 2.0.1
    Uninstalling nonebot2-2.0.1:
      Successfully uninstalled nonebot2-2.0.1
Successfully installed nonebot-adapter-cqhttp-2.0.0b1 nonebot2-2.1.1

尝试重新安装，日志如下
nb plugin install nonebot-plugin-mcqq                       
使用 Python: /Users/justin/lily/.venv/bin/python
Collecting nonebot-plugin-mcqq
  Using cached nonebot_plugin_mcqq-1.2.7-py3-none-any.whl (17 kB)
Requirement already satisfied: nonebot-adapter-onebot>=2.1.1 in ./.venv/lib/python3.9/site-packages (from nonebot-plugin-mcqq) (2.2.3)
Requirement already satisfied: mcqq-tool>=0.0.8 in ./.venv/lib/python3.9/site-packages (from nonebot-plugin-mcqq) (0.1.2)
Requirement already satisfied: nonebot-plugin-guild-patch>=0.2.0 in ./.venv/lib/python3.9/site-packages (from nonebot-plugin-mcqq) (0.2.3)
Requirement already satisfied: nonebot2>=2.0.0 in ./.venv/lib/python3.9/site-packages (from nonebot-plugin-mcqq) (2.0.1)
Requirement already satisfied: aio-mc-rcon>=3.2.0 in ./.venv/lib/python3.9/site-packages (from nonebot-plugin-mcqq) (3.2.0)
Requirement already satisfied: websockets>=10.3 in ./.venv/lib/python3.9/site-packages (from mcqq-tool>=0.0.8->nonebot-plugin-mcqq) (11.0.3)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in ./.venv/lib/python3.9/site-packages (from nonebot-adapter-onebot>=2.1.1->nonebot-plugin-mcqq) (1.0.5)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in ./.venv/lib/python3.9/site-packages (from nonebot2>=2.0.0->nonebot-plugin-mcqq) (2.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in ./.venv/lib/python3.9/site-packages (from nonebot2>=2.0.0->nonebot-plugin-mcqq) (4.7.1)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in ./.venv/lib/python3.9/site-packages (from nonebot2>=2.0.0->nonebot-plugin-mcqq) (0.7.0)
Requirement already satisfied: pydantic[dotenv]<2.0.0,>=1.10.0 in ./.venv/lib/python3.9/site-packages (from nonebot2>=2.0.0->nonebot-plugin-mcqq) (1.10.12)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in ./.venv/lib/python3.9/site-packages (from nonebot2>=2.0.0->nonebot-plugin-mcqq) (1.9.2)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in ./.venv/lib/python3.9/site-packages (from nonebot2>=2.0.0->nonebot-plugin-mcqq) (2.0.1)
Requirement already satisfied: python-dotenv>=0.10.4 in ./.venv/lib/python3.9/site-packages (from pydantic[dotenv]<2.0.0,>=1.10.0->nonebot2>=2.0.0->nonebot-plugin-mcqq) (1.0.0)
Requirement already satisfied: idna>=2.0 in ./.venv/lib/python3.9/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.0.0->nonebot-plugin-mcqq) (3.4)
Requirement already satisfied: multidict>=4.0 in ./.venv/lib/python3.9/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.0.0->nonebot-plugin-mcqq) (6.0.4)
Installing collected packages: nonebot-plugin-mcqq
Successfully installed nonebot-plugin-mcqq-1.2.7

运行nonebot，日志如下
nb run                                                      
使用 Python: /Users/justin/lily/.venv/bin/python
10-08 13:37:45 [SUCCESS] nonebot | NoneBot is initializing...
10-08 13:37:45 [INFO] nonebot | Current Env: prod
10-08 13:37:45 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
10-08 13:37:45 [SUCCESS] nonebot | Succeeded to load plugin "tex" from "plugins.tex"
10-08 13:37:46 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
10-08 13:37:47 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
10-08 13:37:47 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
10-08 13:37:48 [SUCCESS] nonebot | Succeeded to load plugin "nonebot-plugin-random"
10-08 13:37:48 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_help"
10-08 13:37:48 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
10-08 13:37:48 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picstatus"
10-08 13:37:49 [INFO] nonebot_plugin_quote | nonebot_plugin_quote路径配置成功
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_quote"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "render" from "plugins.render"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_eitherchoice"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_repeater"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordcloud"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dialectlist"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_homo_mathematician"
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_withdraw"
10-08 13:37:49 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/Users/justin/miniconda3/envs/bot/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot_plugin_mcqq/__init__.py", line 8, in <module>
    from nonebot.drivers import ASGIMixin
ImportError: cannot import name 'ASGIMixin' from 'nonebot.drivers' (/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/drivers/__init__.py)
10-08 13:37:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
10-08 13:37:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_eventmonitor"
10-08 13:37:50 [SUCCESS] nonebot | Running NoneBot...
10-08 13:37:50 [INFO] uvicorn | Started server process [26247]
10-08 13:37:50 [INFO] uvicorn | Waiting for application startup.
10-08 13:37:50 [INFO] nonebot_plugin_memes | 正在检查资源文件...
10-08 13:37:50 [INFO] nonebot_plugin_datastore | 数据库初始化完成
10-08 13:37:50 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动

**Comment by 17TheWord** [comment]
执行 pip show nonebot2 查看版本号

**Comment by F1Justin** [comment]
看上去是2.1.1（
pip show nonebot2
Name: nonebot2
Version: 2.1.1
Summary: An asynchronous python bot framework.
Home-page: https://nonebot.dev/
Author: yanyongyu
Author-email: yyy@nonebot.dev
License: MIT
Location: /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages
Requires: loguru, pydantic, pygtrie, tomli, typing-extensions, yarl
Required-by: nonebot-adapter-onebot, nonebot-plugin-localstore, nonebot-plugin-memes

**Comment by 17TheWord** [comment]
> 看上去是2.1.1（ pip show nonebot2 Name: nonebot2 Version: 2.1.1 Summary: An asynchronous python bot framework. Home-page: https://nonebot.dev/ Author: yanyongyu Author-email: [yyy@nonebot.dev](mailto:yyy@nonebot.dev) License: MIT Location: /Users/justin/miniconda3/envs/bot/lib/python3.9/site-packages Requires: loguru, pydantic, pygtrie, tomli, typing-extensions, yarl Required-by: nonebot-adapter-onebot, nonebot-plugin-localstore, nonebot-plugin-memes

那不应该无法导入，我这边测试没有问题
