### ISSUE TITLE
【功能建议】支持QQ适配器

### ISSUE THREAD

**Issue by Marze-one** [17TheWord/nonebot-plugin-mcqq#63]
### 插件版本

nonebot-plugin-mcqq

### 插件版本号

v1.2.7

### 功能建议

现在gocq已经停止维护，qsign已经删库，未来qq机器人前途未卜，不知道现在能否支持使用nonebot-adapter-qq官方协议进行QQ频道使用：）

**Comment by 17TheWord** [comment]
有准备支持，但等群token发放之后再做。同时会加入一些其他功能。

**Comment by Marze-one** [comment]
> 有准备支持，但等群token发放之后再做。同时会加入一些其他功能。

**Comment by 17TheWord** [comment]
已知群开放的Bot类型为公域，无法接收每一条消息，将首先单独支持频道私域Bot，群消息滞后。

**Comment by 17TheWord** [comment]
已支持QQ频道私域Bot文字子频道场景

**Comment by 17TheWord** [comment]
官方Bot只能监听@事件，暂不支持

**Comment by St7530** [comment]
> 可以，但你需要自己拿一下群id和超级用户的id

嗯嗯，那太好了，感谢大佬
