### ISSUE TITLE
【功能建议】Fabric 版本的模组配置文件中还没有 `say_way: "说："` 和 `display_groupname: false` 这两个配置项

### ISSUE THREAD

**Issue by Moetazhxi** [17TheWord/nonebot-plugin-mcqq#71]
### 插件版本

MC_QQ

### 插件版本号

MC_QQ_Fabric_1.20.1-2.5.3.jar

### 功能建议

如题，Fabric 版本的模组配置文件中还没有 `say_way: "说："` 和 `display_groupname: false` 这两个配置项，也就是 wiki 中提到的：

![image](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/89954416/64b56ebd-af57-4af7-a7df-017a1de35c80)
![image](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/89954416/54eefa2d-92ec-40be-9e6b-b63564312a0f)

尤其是很想要 `say_way: "说："` 这个功能，要是 `say_way` 中能支持 `\n` 换行就更棒了，不知道有没有计划跟进一下，辛苦啦！

有个换行的话感觉在观感和阅读体验上会好一些，不过其实也无所谓，这个功能无伤大雅。

---

附：现版本 MC_QQ_Fabric_1.20.1-2.5.3.jar 自动生成的配置文件内容如下：
```
# 是否启用插件
# 默认启用
enable_mc_qq: true

# 是否启用重连提示
# 默认开启
enable_reconnect_msg: true

# 请在冒号后填写 WebSocket 地址。
# 默认：ws://127.0.0.1:8080/minecraft/ws
websocket_url: "ws://127.0.0.1:8080/minecraft/ws"

# 是否启用 玩家命令事件监听
# 开启后，当玩家输入命令时，Bot 会推送命令信息
# 默认不启用
command_message: false

# 是否启用 玩家死亡事件监听
# 开启后，当玩家死亡时，Bot 会推送信息
# 默认启用
death_message: true

# 是否启用 加入/离开 服务器监听
# 开启后，当玩家 加入/离开 服务器时，Bot 会推送信息
# 默认打开
# 例如：
#   17TheWord 加入了服务器
#   17TheWord 离开了服务器
join_quit: true

# 服务器名称
# 当有多个服务器连接到 Bot 时，用于区分。
# 如果是多个服务器，请务必对各个服务器设置不同的服务器名称。
# 默认值为：Server
server_name: "Server"
```

**Comment by 17TheWord** [comment]
想起来貌似是已经取消了，这些已经不归MC这边管了

**Comment by 17TheWord** [comment]
> 想起来貌似是已经取消了，这些已经不归MC这边管了

wiki已删除这些字段

**Comment by Moetazhxi** [comment]
> > 想起来貌似是已经取消了，这些已经不归MC这边管了
> 
> wiki已删除这些字段，你可以改Python那边的代码来实现 `say_way`
> 
> 后续可以考虑改为配置项

喔喔是这样啊，感谢解答！那我就把这个 close 了

**Comment by 17TheWord** [comment]
> > 想起来貌似是已经取消了，这些已经不归MC这边管了
> 
> wiki已删除这些字段，你可以改Python那边的代码来实现 `say_way`
> 
> 后续可以考虑改为配置项

- 已添加 `say_way` 为配置项，在 [wiki](https://github.com/17TheWord/nonebot-plugin-mcqq/wiki/3.-nonebot%E7%AB%AF%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 可以查看，`mc_qq_say_way = "："`
更新 `mcqq-tool` 即可，`pip install -U mcqq-tool`
- 同时mod端已支持广播带有颜色等修饰的消息，需要mod版本为 `2.5.4` 以及以上
