### ISSUE TITLE
【错误反馈】MC to QQ不行，但QQ to MC消息成功

### ISSUE THREAD

**Issue by Wu-jiyan** [17TheWord/nonebot-plugin-mcqq#75]
### 运行环境

Windows Server 2019、Python3108、PaperSpigot-1.20.1

### NB插件及版本号

2.5.4

### MC插件及版本号

2.5.4

### 遇到问题：
玩家在QQ群中发送消息，服务器中能够收到消息，并且响应正常
但玩家在MC中发送消息、进入推出，QQ群中却不能收到消息，后台无报错
检查配置并一切正常

**NB的输出：**
`02-14 22:58:06 [SUCCESS] nonebot | Minecraft PCE | [PlayerQuitEvent]: @Wu_jiyan Quit [PCE]`
`02-14 22:58:06 [DEBUG] nonebot | Checking for matchers in priority 1...`
`02-14 22:58:06 [DEBUG] nonebot | Checking for matchers in priority 4...`
`02-14 22:58:06 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_mcqq.minecraft_msg, lineno=12)`
`02-14 22:58:06 [DEBUG] nonebot | Running Matcher(type='notice', module=nonebot_plugin_mcqq.minecraft_msg, lineno=12)`
`02-14 22:58:06 [DEBUG] nonebot | Running handler Dependent(call=handle_mc_notice)`
`02-14 22:58:06 [DEBUG] nonebot | OneBot V11 | Calling API send_group_msg`
`02-14 22:58:06 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_mcqq.minecraft_msg, lineno=12) running complete`

**MC服务器后台无任何输出、报错**

**Onebot** V11 协议适配器输出log：
`API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan 加入了游戏","action":"send_group_msg"} `
`API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan：w3ertsfwas","action":"send_group_msg"} `
`API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan 退出了游戏","action":"send_group_msg"} `
但消息都没有发出
奇怪的是使用/mcc、/mca等指令，BOT正常回复，后台LOG:
`API receive post:{"user_id":3xxxx32800,"group_id":6xxxx4368,"message_type":"group","message":[{"type":"text","data":{"text":"返回结果：\n发送至服务器：PCE 命令：test 结果：成功"}}],"action":"send_group_msg"} `

这两个LOG并不相同，很奇怪

### 如何复现：

这个我并不清楚awa，我的服务器安装了与聊天相关插件：`TRCHAT`，但是我删除后服内消息不上报了，很玄学，望大佬帮助~

### 期望结果：

BOT正常输出MC中玩家聊天、登录、登出消息到QQ群中

**Comment by 17TheWord** [comment]
用的是拉格朗吗？（我没有用过拉格朗）

`API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan 加入了游戏","action":"send_group_msg"} `
`API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan：w3ertsfwas","action":"send_group_msg"} `
`API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan 退出了游戏","action":"send_group_msg"}`
但根据这三行能看出来已经请求了发送消息的API，但并没有发到群内。
命令能正常回复的话，emmm，感觉问题不在插件和框架，可能是协议端的问题？

**Comment by Wu-jiyan** [comment]
> 用的是拉格朗吗？（我没有用过拉格朗）
> 
> `API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan 加入了游戏","action":"send_group_msg"} ` `API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan：w3ertsfwas","action":"send_group_msg"} ` `API receive post:{"group_id":6xxxx4368,"message":"Wu_jiyan 退出了游戏","action":"send_group_msg"}` 但根据这三行能看出来已经请求了发送消息的API，但并没有发到群内。 命令能正常回复的话，emmm，感觉问题不在插件和框架，可能是协议端的问题？

我的协议端是LLONEBOTAPI，基于LLAPI的NTQQ，之前使用的V2版本有该错误，现在更新了V3修复了，我更换后问题已解决，非常抱歉由于协议端适配错误而麻烦您，谢谢您的回答！

**Comment by Wu-jiyan** [comment]
问题解决
