### ISSUE TITLE
【功能建议】Fabric 模组（MC_QQ_Fabric_1.20.1-2.5.4.jar）添加指令手动重连的功能

### ISSUE THREAD

**Issue by Moetazhxi** [17TheWord/nonebot-plugin-mcqq#80]
### 插件版本

MC_QQ

### 插件版本号

v2.5.4

### 功能建议

**希望可以添加在游戏控制台中输入指令，来手动重连至 nonebot 的功能。**

我看到插件本身是会断线重连的，但是如果 nonebot 异常断开连接，这时候就不会重连了。

这个是单纯猜测，我不是很清楚。因为在大部分情况下断开连接之后，后台会刷屏显示第 x 次重连至什么什么的信息，这个时候如果重启 nonebot 后插件会成功自动重连。但是有的时候却完全不会提示，也不会主动重连，这就导致我想重连时候我就必须重启服务器才可以，所以我想或许可以加一个什么指令，让我手动重连。

而且有的时候关掉 nonebot 后服务器后台会一直刷屏：第 x 次重连至什么什么，这些信息占用了日志的一大半。

所以我个人的建议是或许可以设置一个重连最大次数，比如 60 次，每次相隔 10 秒（十分钟内断线重连）之类的，既能确保后台不被刷屏太厉害，也能有及时断线重连的功能。当超时或者因为异常导致不自动重连的时候，就让用户手动输入指令来连接，我觉得是一种可行的解决方案。

当然也只是我个人这么想而已，或许有更多更好的解决方法，也可能是只有我一个人遇到这种问题😢

最后感谢作者开发的插件，帮太大忙了，先给你磕一个🙉

**Comment by 17TheWord** [comment]
重连机制因为能力问题写的较为shit，也有考虑用更优雅的方式实现。
命令系统一开始就在计划中的，奈何能力问题且mc端较多就一直搁置了，目前没有其他要更新的功能，会在下次尝试加上。
重连信息有配置项可以关闭。
感谢你的建议。

**Comment by 17TheWord** [comment]
已在 [`Fabric v2.5.5`](https://github.com/17TheWord/MC_QQ_Fabric/releases/tag/v2.5.5) 添加试验性命令重连，后续会在另外两端添加重连功能
使用命令时（已设置权限为 `2`，OP可用），只有连接未打开时才会重连
重连日志将在之后的更新中默认关闭，可在配置项中打开

**Comment by Moetazhxi** [comment]
> 已在 [`Fabric v2.5.5`](https://github.com/17TheWord/MC_QQ_Fabric/releases/tag/v2.5.5) 添加试验性命令重连，后续会在另外两端添加重连功能 使用命令时（已设置权限为 `2`，OP可用），只有连接未打开时才会重连 重连日志将在之后的更新中默认关闭，可在配置项中打开

辛苦了！！！
