### ISSUE TITLE
【错误反馈】server_dict传入时报类型错误

### ISSUE THREAD

**Issue by p0rt39** [17TheWord/nonebot-plugin-mcqq#89]
### 运行环境

Winserver2022 22H2, Python 3.12, Mohist 1.20.1

### NB插件及版本号

2.5.6

### MC插件及版本号

2.6.6 Spigot

### 错误描述

在加载插件时报
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[Config]
__root__ -> mc_qq -> server_dict
  value is not a valid dict (type=type_error.dict)
使用wiki中的模板和自编辑传入参数mc_qq__server_dict均会报错
使用的pydantic是经过降级的1.10.8版本

**Comment by 17TheWord** [comment]
填写的dict是否携带了注释？删除注释以符合Json标准
```env
"Server": { # 服务器名，与 mc 端配置文件同步
```

改为
```env
"Server": {
```

**Comment by 17TheWord** [comment]
长时间没有回应，将关闭issue，若扔有问题请再次打开
