### ISSUE TITLE
【功能建议】适配PurPur端显示tps的方式

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [17TheWord/nonebot-plugin-mcqq#95]
### 插件版本

nonebot-plugin-mcqq

### 插件版本号

2.5.7

### 功能建议

在群内对服务器发送查看tps的命令时，返回的信息如下
![Image_1716820073233](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/86163024/006c5fec-374a-4870-96bd-d02fb39816d8)
但PurPur端在服务端发送tps指令后返回的信息是这样的
![image](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/86163024/8e6264a6-a9aa-4ffb-950b-bcb35cbeae9c)

### 额外信息（可选）

适配PurPur端显示tps的方式，方便在群内查看服务器当前tps

**Comment by 17TheWord** [comment]
与服务端无关，tps只与rcon有关
