### ISSUE TITLE
【功能建议】从同步到QQ的消息中过滤掉mcdreforged命令

### ISSUE THREAD

**Issue by yokinanya** [17TheWord/nonebot-plugin-mcqq#96]
### 插件版本

nonebot-plugin-mcqq

### 插件版本号

v2.5.7

### 功能建议

从同步到QQ的消息中过滤掉 [MCDReforged ](https://github.com/MCDReforged/MCDReforged)以及相关插件的命令，一般为 `!!` 开头

**Comment by 17TheWord** [comment]
能否提供几段传递过来的命令的Json？

**Comment by 17TheWord** [comment]
如果传递的是玩家消息事件的话，只需要过滤掉 `!!` 开头的消息就好了，你可以直接对插件进行 `pr` 或等待更新

**Comment by yokinanya** [comment]
> 如果传递的是玩家消息事件的话，只需要过滤掉 `!!` 开头的消息就好了，你可以直接对插件进行 `pr` 或等待更新

它传递的就是玩家消息事件
