### ISSUE TITLE
【功能建议】群内向服务器发送指令返回的信息如果使用了文字高亮，则使用图片渲染便于阅读

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [17TheWord/nonebot-plugin-mcqq#98]
### 插件版本

nonebot-plugin-mcqq

### 插件版本号

2.5.7

### 功能建议

群内向服务器发送的指令所返回的信息如果使用了文字高亮，则使用图片渲染便于阅读
例如服务端如果添加了essentialsx插件，向服务端发送指令返回的信息会使用颜色高亮
![Screenshot_20240601-004854_EDIT_1717174154937](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/86163024/4fb75241-6709-4d01-bc87-90393e131295)
但如果由群内向服务器发送指令，返回的信息是这样的，带有高亮颜色代码，不便于阅读
![Image_1717174089521](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/86163024/7aa8ac7b-d568-4065-b076-56c7784333a6)

### 额外信息（可选）

便于在群内查看发送的指令所返回的信息

**Comment by 17TheWord** [comment]
将在后续版本尝试支持

**Comment by xiao-k233** [comment]
有点难实现，我的想法是直接把转义符去了

**Comment by 17TheWord** [comment]
已在 [`v2.5.9`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v2.5.9) 使用正则过滤颜色字符

**Comment by 17TheWord** [comment]
暂时这样解决，渲染图片等有空再试试

**Comment by 17TheWord** [comment]
![ORBXB6AX(2Z5DIZ((O617NE](https://github.com/user-attachments/assets/dc2a608a-c330-4568-a5fc-5b94198f9346)
![JM {B LNX3EB~P@_BJKOCAF](https://github.com/user-attachments/assets/e898f361-f227-4dd2-aa96-32eee789da53)
![I8@(9Q1}3%PLBX4IJ0 B2O9](https://github.com/user-attachments/assets/6c0a40c4-6452-41f8-a8c7-3c1e76917c0b)
这种样式如何，图片尺寸或者文字大小是否需要再调整？

**Comment by 17TheWord** [comment]
#120

**Comment by YuYue-Amatsuki** [comment]
> 已在 [`v2.5.9`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v2.5.9) 使用正则过滤颜色字符

能否将死亡信息以及聊天信息的颜色字符过滤？
如图
![Image_1725102905701.jpg](https://github.com/user-attachments/assets/02d4fe6f-49ef-44a5-bdb7-d0691b75d8e2)

**Comment by 17TheWord** [comment]
这是什么端，为什么这都带颜色的，稍等

**Comment by YuYue-Amatsuki** [comment]
> 这是什么端，为什么这都带颜色的，稍等

插件端安装了怪物和聊天颜色插件

**Comment by 17TheWord** [comment]
返回图片渲染已经使用pillow简易实现，暂未测试，该功能需要安装pillow作为拓展，同时查看wiki新增的i配置项

**Comment by 17TheWord** [comment]
> > 已在 [`v2.5.9`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v2.5.9) 使用正则过滤颜色字符
> 
> 能否将死亡信息以及聊天信息的颜色字符过滤？ 如图 ![Image_1725102905701.jpg](https://private-user-images.githubusercontent.com/86163024/363409660-02d4fe6f-49ef-44a5-bdb7-d0691b75d8e2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDMyODQsIm5iZiI6MTcyNTEwMjk4NCwicGF0aCI6Ii84NjE2MzAyNC8zNjM0MDk2NjAtMDJkNGZlNmYtNDllZi00NGE1LWJkYjctZDA2OTFiNzVkOGUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDExMTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNTQ2YjJlNzhiYTNhMzU3NTk3NGQyN2E0MWRjMjk5MmM4NmFlZGM5NzQwNTg1MzdjNzcwMDdiNzdlNWE0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EuG0vffLBzLPHleFpynj26sJZ2QqAbgFCNaWGQcc-bs)

更新 `mcqq-tool` 至 `v1.2.8` 即可, `pip install -U mcqq-tool`

**Comment by 17TheWord** [comment]
已更新 [`v2.6.2`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v2.6.2)

**Comment by 17TheWord** [comment]
可能是pyd版本问题

**Comment by 17TheWord** [comment]
尝试 `pip install mcqq-tool==1.3.0`
